### ISSUE TITLE
Support for "clear all notifications"

### ISSUE THREAD

**Issue by TosinHaastrup** [teodosii/react-tweenful#8]
I have mutliple buttons onClick which calls a function. The function will call the react-notification-component.
If I click on the same button the notification will continously reappear which is find, the slight problem is when I click on another button the old notification remains. Is there a way I can clear all notifications within that function?

**Comment by teodosii** [comment]
You could post into the other repository (this is react-tweenful for animating, not for notifications), an example would also help. Thank you
